# Generated by Django 5.0.4 on 2024-05-07 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('bachid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Batch')),
                ('course', models.CharField(max_length=20, verbose_name='Course')),
                ('classname', models.CharField(max_length=50, null=True, verbose_name='Class Name')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('classname', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=132)),
                ('email', models.CharField(max_length=130)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_num', models.IntegerField(primary_key=True, serialize=False, verbose_name='Room Number')),
                ('seats', models.IntegerField(verbose_name='Total Seats')),
                ('gate', models.CharField(default='left', max_length=7, verbose_name='Gate Side')),
                ('dis', models.TextField(blank=True, verbose_name='Room Discription')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('phone_no', models.CharField(max_length=10, unique=True, verbose_name='Phone Number')),
                ('full_name', models.CharField(max_length=50, verbose_name='Name')),
                ('gnder', models.IntegerField(blank=True, default='4', verbose_name='Gender')),
                ('dob', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOB')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_subadmin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('auth_token', models.CharField(blank=True, max_length=200)),
                ('auth_token_time', models.CharField(default='None', max_length=50)),
                ('propath', models.CharField(blank=True, default='not', max_length=100, null=True, verbose_name='Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DateOfClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateField(verbose_name='Date')),
                ('subjct', models.CharField(max_length=30, verbose_name='Subject')),
                ('value', models.BooleanField(default=False, verbose_name='Value')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seating.classes', verbose_name='Class')),
            ],
        ),
        migrations.CreateModel(
            name='RoomsRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.IntegerField(verbose_name='Row Number')),
                ('desks', models.IntegerField(verbose_name='Desk in Row')),
                ('capicity', models.IntegerField(verbose_name='Capacity')),
                ('room_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seating.rooms', verbose_name='Room Number')),
            ],
        ),
        migrations.CreateModel(
            name='Stundets',
            fields=[
                ('rollnum', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Roll Number')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='E-mail')),
                ('bachid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seating.batch', verbose_name='Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjct', models.CharField(max_length=30, verbose_name='Subject')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seating.classes', verbose_name='Class')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='class_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Class Admin'),
        ),
        migrations.CreateModel(
            name='AttendUser',
            fields=[
                ('rollnum', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Roll Number')),
                ('notify', models.BooleanField(default=True)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seating.classes', verbose_name='Class')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('subject', models.CharField(max_length=30, verbose_name='Subject')),
                ('value', models.IntegerField(default=3, verbose_name='Value')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Email')),
            ],
        ),
    ]
